children:
  -
    id: 964d594b-7daa-c1dc-ecce-5f41293c6a3b
    type: section
    subtype: false
    title: Header
    attributes: {  }
    children:
      -
        id: a4efbce3-8ed0-aa1d-c694-033ba3b4142b
        type: container
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 7d5d84ad-65be-bb51-49c3-3f4cfd50fb49
            type: grid
            subtype: false
            title: Untitled
            attributes: {  }
            children:
              -
                id: 677a4709-926d-2855-ac2b-ee3a9757e305
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 100
                children:
                  -
                    id: 023d5760-d1eb-609b-cc78-c6fa93a72adf
                    type: particle
                    subtype: logo
                    title: Logo
                    attributes:
                      enabled: 1
                      image: 'gantry-assets://images/gantry5-logo.png'
                      class: gantry-logo
                    children: {  }
  -
    id: 7116256b-b935-c45f-cfa8-5ab24cf21965
    type: section
    subtype: false
    title: Navigation
    attributes: {  }
    children:
      -
        id: 3a30abb9-2767-1dfb-e31f-5cf322337da0
        type: container
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 194e7764-70a1-b39d-d80b-bfb047694af5
            type: grid
            subtype: false
            title: Untitled
            attributes: {  }
            children:
              -
                id: 09902402-6e28-c1e7-1b37-50cb1e73ca33
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 100
                children:
                  -
                    id: ce1b5a90-df19-c069-ffd0-98f1d82117b0
                    type: particle
                    subtype: menu
                    title: Menu
                    attributes:
                      enabled: 1
                    children: {  }
  -
    id: 03f7d369-8525-4c81-7f0d-e00ba3eae506
    type: section
    subtype: false
    title: Main
    attributes: {  }
    children:
      -
        id: 440b0add-3bca-ca55-6ce3-ffc6317a5a76
        type: container
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: b7cb8979-9d49-e3b6-e36b-d97a19e3e035
            type: grid
            subtype: false
            title: Untitled
            attributes: {  }
            children:
              -
                id: dc085cf7-9be7-5de0-27e8-4455ed13bba1
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 100
                children:
                  -
                    id: fc6c7aed-b44a-e5ec-bb76-ed6f2981e47f
                    type: position
                    subtype: false
                    title: Breadcrumbs
                    attributes:
                      enabled: 1
                      key: breadcrumbs
                      title: Breadcrumbs
                    children: {  }
          -
            id: 8b351932-91ba-8395-e06b-f8eaa0efed85
            type: grid
            subtype: false
            title: Untitled
            attributes: {  }
            children:
              -
                id: 29568536-e6aa-5aed-de6c-18f7acbf1a4d
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 100
                children:
                  -
                    id: 5e3e4188-26d6-3f78-9617-8fe6df77f84f
                    type: position
                    subtype: false
                    title: Global_messages
                    attributes:
                      enabled: 1
                      key: global_messages
                      title: Global_messages
                    children: {  }
          -
            id: 1900441b-5657-94b5-2561-ca3ea5974ec8
            type: grid
            subtype: false
            title: Untitled
            attributes: {  }
            children:
              -
                id: f6a49934-54e5-5594-487e-b009caab9482
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 100
                children:
                  -
                    id: a97ad737-a90e-3e65-d360-fa92679b5ef4
                    type: pagecontent
                    subtype: false
                    title: Pagecontent
                    attributes:
                      enabled: 1
                    children: {  }
  -
    id: 10ff44f5-d2af-44ed-4080-74f53635f496
    type: section
    subtype: false
    title: Footer
    attributes: {  }
    children:
      -
        id: 1b201ee8-ed9c-3ede-e613-8628ce45dbcd
        type: container
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 9ece9287-eb34-baf1-41e0-007cc24bc0dd
            type: grid
            subtype: false
            title: Untitled
            attributes: {  }
            children:
              -
                id: a9513264-1e08-3cde-4c66-a1d42ca667e4
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 100
                children:
                  -
                    id: f60495eb-f1bb-5c8f-f114-ed8ad8c58ce9
                    type: position
                    subtype: false
                    title: Footer
                    attributes:
                      enabled: 1
                      key: footer
                      title: Footer
                    children: {  }
          -
            id: 8849d5a9-33e4-87a8-ade2-5a02293327cb
            type: grid
            subtype: false
            title: Untitled
            attributes: {  }
            children:
              -
                id: 1a785706-62de-bbca-9d9d-13cb3ca0f4d0
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 40
                children:
                  -
                    id: a48aec5a-e29a-5819-a22b-f1a9b3518032
                    type: particle
                    subtype: copyright
                    title: Copyright
                    attributes:
                      enabled: 1
                    children: {  }
              -
                id: 93961ab9-04e3-2e80-cb80-f1b3f4977095
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 30
                children:
                  -
                    id: 0592d998-7e5b-f25d-2335-97eaf8be5277
                    type: spacer
                    subtype: false
                    title: Spacer
                    attributes:
                      enabled: 1
                    children: {  }
              -
                id: 2ac5a009-d872-15b9-a3da-287b174a5a2d
                type: block
                subtype: false
                title: Untitled
                attributes:
                  size: 30
                children:
                  -
                    id: ae84a898-9e28-3b92-0327-a38593fd35f1
                    type: particle
                    subtype: branding
                    title: Branding
                    attributes:
                      enabled: 1
                    children: {  }
  -
    id: b81f55bf-64d5-7b6f-2018-ed3f22daea4f
    type: offcanvas
    subtype: false
    title: Offcanvas
    attributes:
      name: 'Offcanvas Section'
    children:
      -
        id: 1d77dfdd-a44c-4d76-8ebf-6b683de4748b
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children:
          -
            id: 35c4d946-c99e-43ad-b5b1-6c7ae5ae1aab
            type: block
            subtype: false
            title: Untitled
            attributes:
              size: 100
              extra: {  }
            children:
              -
                id: dcbf7c39-89a1-41bf-8878-92020f172dbc
                type: particle
                subtype: mobile-menu
                title: "\n                                Mobile Menu\n                            "
                attributes:
                  enabled: 1
                children: {  }
  -
    id: 4ebf163b-da54-172d-1407-439dd778065e
    type: atoms
    subtype: false
    title: Atoms
    attributes:
      name: 'Atoms Section'
    children:
      -
        id: f6f80800-9778-4ce0-b3a7-155f9286c154
        type: grid
        subtype: false
        title: Untitled
        attributes: {  }
        children: {  }
