name: Inheritance
description: Nothing to inherit tab
type: empty.inheritance

form:
  fields:
    _note:
      type: separator.note
      class: alert alert-info blocksize-note
      content: 'You can inherit sections and particles from Base Outline.'
    _note2:
      type: separator.note
      class: alert alert-success blocksize-note
      content: 'No Outline is currently inheriting this item.'
