name: PHP Tests

on:
  push:
    branches-ignore: [ master, main ]
  pull_request:
    branches-ignore: [ master, main ]

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [ 8.3, 8.2, 8.1 ]
        os: [ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: opcache, gd, zip
          tools: composer:v2, phpunit
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install packages
        run: |
          sudo apt-get -y update -qq  < /dev/null > /dev/null
          sudo apt-get -y install -qq git zip php-zip < /dev/null > /dev/null
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir -d bin/builder)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Build Gantry packages
        run: composer build-dev
      - name: Run PHP 8.3 compatibility tests
        if: matrix.php == '8.3'
        run: ./tests/php83/scripts/run-tests.sh

#  slack:
#      name: Slack
#      needs: unit-tests
#      runs-on: ubuntu-latest
#      if: always()
#      steps:
#        - uses: technote-space/workflow-conclusion-action@v2
#        - uses: 8398a7/action-slack@v3
#          with:
#             status: failure
#             fields: repo,message,author,action
#             icon_emoji: ':octocat:'
#             author_name: 'Github Action Tests'
#             text: '💥 Automated Test Failure'
#          env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#          if: env.WORKFLOW_CONCLUSION == 'failure'
